### ISSUE TITLE
Circuit Construction Kit: AC Main checklist

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-ac#1]
# Circuit Construction Kit: AC master checklist

## Design
- [x] **Sim folder and design doc created** (Date: 12/18/2018)
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Legacy sim docs/info gathered**
  - [x] [Sim suggestions doc](https://phet.unfuddle.com/a#/projects/9404/notebooks/3863/pages/105821) reviewed
  - [x] Unfuddle tickets reviewed ([searching tickets](https://github.com/phetsims/phet-info/blob/master/issue-info/unfuddle-ticket-search.md))
- [ ] **Learning goals and standards identified** (Date: //)
- [ ] **Design concept complete**  (Date: //)
- [ ] **Wireframes complete** (Date: //) 
- [ ] **Mockups complete** (Date: //) 
  - [ ] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion** 
- [ ] **Interviews complete** (Date: //) 
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //) 
  - [ ] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [ ] No new feature requests
- [ ] **Pre-publication items** 
  - [ ] Auxilary screenshots (up to 3 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [ ] Accessibility features
  - [ ] Email announcement language
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Sim primer draft
  - [ ] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [ ] LoL [metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [ ] **Post-publication items** 
  - [ ] Share new features, design challenges, and treats with group!
  - [ ] Review legacy gold star activities, copy over if appropriate
  - [ ] Email announcement language
  - [ ] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [ ] Hold postmortem if applicable (Date: //) 

## Implementation
- [x] **Repository created** (Date: 2/10/2019)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] Use `grunt create-sim` in perennial (see `--help` for arguments) to create the repository structure
  - [x] Collaborators added (Developer team, QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
- [x] **Development started** (Date: 2/10/2019)
- [x] **Sim is "feature complete"** (Date: 01/11/2021)
- [x] **Code review completed** (Date: 05/19/2021)
- [x] **Pre-publication items**
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots))
  - [x] Verify credits
  - [x] Notify MP if legacy simulation page URL doesn't follow naming convention (simulations/simulation-name)
- [ ] **Published** (Date: //)
  - [ ] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [ ] **Legacy sim tested for bugs**; issues reported in repo
- [ ] **Dev testing started** (Date: //) 
- [ ] **Dev testing complete** (Date: //) 
- [ ] **First RC published** (Date: //)
  - [ ] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [ ] **RC testing completed** (Date: //)

**Comment by samreid** [comment]
From the new repo checklist:

> - [ ] Add to perennial/data/active-repos, commit and push. (after a few minutes, an automated process should update the other files under perennial/data. pull perennial so you can find the sim in phetmarks)

It has been a while and perennial hasn't updated yet.  If it doesn't update soon, I'll create a new issue for investigation.
