### ISSUE TITLE
Create Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-ac#9]
For #1 

- [x] Query parameters: `screens`, `audio`, `supportsPanAndZoom`, and relevant [public query parameters](https://github.com/phetsims/circuit-construction-kit-common/blob/master/js/CCKCQueryParameters.ts)
- [x] https://github.com/phetsims/circuit-construction-kit-common/issues/245
- [x] Ammeters & signs: https://github.com/phetsims/circuit-construction-kit-common/issues/508, https://github.com/phetsims/circuit-construction-kit-common/issues/606
- [x] https://github.com/phetsims/circuit-construction-kit-common/issues/429
- [x] Dynamics may require model to be stepped forward when paused (fuse/dog) - https://github.com/phetsims/circuit-construction-kit-common/issues/572 
- [x] Energy in an inductor is instantly dissipated when the circuit is broken - https://github.com/phetsims/circuit-construction-kit-common/issues/570
- [x] Electrons near parallel junctions can appear to overlap/slingshot - https://github.com/phetsims/circuit-construction-kit-common/issues/768
- [x] Spikes can occur in the voltage and current charts under certain circumstances - https://github.com/phetsims/circuit-construction-kit-common/issues/779
- [x] When paused, time will step forward 1E-6 seconds when the sim is interacted with (close a switch, move slider thumb, etc.). - https://github.com/phetsims/circuit-construction-kit-common/issues/772
- [x] The capacitor model can behave strangely in situations with no/very low resistance. For example, https://github.com/phetsims/circuit-construction-kit-common/issues/787 https://github.com/phetsims/circuit-construction-kit-common/issues/788

**Comment by arouinfar** [comment]
The teacher tips have been uploaded, closing.
